[package]
name = "cis_client"
version = "0.3.1"
authors = ["Florian Merz <flomerz@gmail.com>"]
edition = "2018"

[dependencies]
shared-expiry-get = "0.0.1"
cis_profile = { git = "https://github.com/fiji-flo/cis_profile-rust", version = "0.3.1", branch = "0.3.1", features = ["aws", "vendored", "well_known"] }
reqwest = "0.9"
biscuit = "0.4"
chrono = "0.4"
serde = "1.0.80"
serde_json = "1.0.32"
serde_derive = "1.0.80"
percent-encoding = "2.1"
failure = "0.1"
failure_derive = "0.1"
futures = "0.1"
tokio = "0.1"
