[package]
name = "cis_client"
version = "0.1.0-beta.1"
authors = ["Florian Merz <flomerz@gmail.com>"]
edition = "2018"

[dependencies]
shared-expiry-get = "0.0.1"
cis_profile = { git = "https://github.com/fiji-flo/cis_profile-rust", version = "0.0.3", branch = "ring-14", features = ["graphql", "aws", "vendored", "well_known"] }
reqwest = "0.9"
chrono = "0.4"
serde = "1.0.80"
serde_json = "1.0.32"
serde_derive = "1.0.80"
biscuit = "0.2"
percent-encoding = "1.0"
failure = "0.1.5"
failure_derive = "0.1.5"
futures = "0.1"
