[package]
name = "cis_client"
version = "0.3.1"
authors = ["Florian Merz <flomerz@gmail.com>"]
edition = "2018"

[dependencies]
shared-expiry-get = { git = "https://github.com/fiji-flo/shared-expiry-get", version = "0.1.0", branch = "0.1.0" }
cis_profile = { git = "https://github.com/fiji-flo/cis_profile-rust", version = "0.3.1", branch = "0.3.1", features = ["aws", "vendored", "well_known"] }
reqwest =  { version = "0.10", features = ["json"] }
biscuit = "0.4"
chrono = "0.4"
serde = "1.0.80"
serde_json = "1.0.32"
serde_derive = "1.0.80"
percent-encoding = "2.1"
failure = "0.1"
failure_derive = "0.1"
futures = "0.3"
tokio = "0.2"
log = "0.4"
